
const dPadding = '10';
const placeholder = [
    { "postId": 0, "userId": 0, "user": "Joel", "message": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin sed orci vel dui iaculis finibus. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. In aliquam orci sed odio laoreet, at placerat purus sed.", "hasImage": true, "imageSrc": "https://www.freecodecamp.org/news/content/images/2022/09/jonatan-pie-3l3RwQdHRHg-unsplash.jpg" },
    { "postId": 1, "userId": 1, "user": "Pedro", "message": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin sed orci vel dui iaculis finibus. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. In aliquam orci sed odio laoreet, at placerat purus sed.", "hasImage": false, "imageSrc": "https://www.freecodecamp.org/news/content/images/2022/09/jonatan-pie-3l3RwQdHRHg-unsplash.jpg" },
    { "postId": 2, "userId": 2, "user": "Laura", "message": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin sed orci vel dui iaculis finibus. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. In aliquam orci sed odio laoreet, at placerat purus sed.", "hasImage": false, "imageSrc": "https://www.freecodecamp.org/news/content/images/2022/09/jonatan-pie-3l3RwQdHRHg-unsplash.jpg" },
    { "postId": 3, "userId": 3, "user": "Victor", "message": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin sed orci vel dui iaculis finibus. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. In aliquam orci sed odio laoreet, at placerat purus sed.", "hasImage": true, "imageSrc": "https://www.freecodecamp.org/news/content/images/2022/09/jonatan-pie-3l3RwQdHRHg-unsplash.jpg" },
    { "postId": 4, "userId": 4, "user": "Saul", "message": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin sed orci vel dui iaculis finibus. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. In aliquam orci sed odio laoreet, at placerat purus sed.", "hasImage": false, "imageSrc": "https://www.freecodecamp.org/news/content/images/2022/09/jonatan-pie-3l3RwQdHRHg-unsplash.jpg" },
    { "postId": 5, "userId": 0, "user": "Joel", "message": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin sed orci vel dui iaculis finibus. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. In aliquam orci sed odio laoreet, at placerat purus sed.", "hasImage": true, "imageSrc": "https://www.freecodecamp.org/news/content/images/2022/09/jonatan-pie-3l3RwQdHRHg-unsplash.jpg" },
    { "postId": 6, "userId": 6, "user": "Camila", "message": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin sed orci vel dui iaculis finibus. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. In aliquam orci sed odio laoreet, at placerat purus sed.", "hasImage": false, "imageSrc": "https://www.freecodecamp.org/news/content/images/2022/09/jonatan-pie-3l3RwQdHRHg-unsplash.jpg" },
    { "postId": 7, "userId": 7, "user": "Laura", "message": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin sed orci vel dui iaculis finibus. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. In aliquam orci sed odio laoreet, at placerat purus sed.", "hasImage": true, "imageSrc": "https://www.freecodecamp.org/news/content/images/2022/09/jonatan-pie-3l3RwQdHRHg-unsplash.jpg" },
    { "postId": 8, "userId": 8, "user": "Juan", "message": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin sed orci vel dui iaculis finibus. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. In aliquam orci sed odio laoreet, at placerat purus sed.", "hasImage": true, "imageSrc": "https://www.freecodecamp.org/news/content/images/2022/09/jonatan-pie-3l3RwQdHRHg-unsplash.jpg" }
]
export { dPadding, placeholder }